In [1]:
import pandas as pd

# import thoes two files 
df = pd.read_csv('data/survey_results_public.csv')
schecma_df = pd.read_csv('data/survey_results_schema.csv')

# Sorting

In [25]:
# sorting by index
df.sort_index(ascending=False)


# for sorting by a specific column
df.sort_values(by='ConvertedComp', ascending=False)


# sorting with multiple columns =====> we can use inplace=True
df.sort_values(by=['Country', 'ConvertedComp'], ascending=[False, False]).head(4)


# sorting the 7 smallest salaries in the survey
df['ConvertedComp'].nsmallest(7)


# sorting the 7 highest salaries in the survey
df['ConvertedComp'].nlargest(7)


# OR we can like below if u want to have his survey as well.
df.nlargest(3, 'ConvertedComp')


# insase u can NOT use the inplace=True JUST assigne it to the old df

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
121,123,I am a developer by profession,Yes,26.0,12,Weekly,120000.0,2000000.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Flask;jQuery;React.js,Spring,Just as welcome now as I felt last year,36.0,8,3
123,125,"I am not primarily a developer, but I write co...",Yes,41.0,30,Monthly,200000.0,2000000.0,United States,United States dollar,...,Easy,Appropriate in length,No,NaN,NaN,NaN,Just as welcome now as I felt last year,40.0,11,11
191,193,I am a developer by profession,Yes,29.0,16,Weekly,120000.0,2000000.0,United States,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,13,7